.TH ZULA-CLI "1" "June 2016" "zula-cli 0.12"
.SH NAME
zula-cli \- a remote procedure call client for Zula Core. 
.SH SYNOPSIS
zula-cli [options] <command> [params] \- Send command to Zula Core. 
.TP
zula-cli [options] help \- Asks Zula Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the zula-cli program. zula-cli is an RPC client used to send commands to Zula Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBzulad\fP, \fBzula.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
